### ISSUE TITLE
Just a wording issue: non commercial licenses are not open source

### ISSUE THREAD

**Issue by maxhbr** [Ladniy/jiran-ble-lite#3]
Hey @Ladniy,

I really like your design but would like to flag a wording issue here:

https://github.com/Ladniy/jiran-ble-lite/blob/7963cccd422c94a021ac304dafcbd5ea8da987a1/README.md?plain=1#L7

A non-commercial license is by definition not an open source license, can you maybe fix that here? E.g. write `"free to use"`. See for example https://mifactori.de/non-commercial-is-not-open-source/

**Comment by Ladniy** [comment]
Fixed, thank you!
