### ISSUE TITLE
You could use hierarchical sheets, so you don't have to copy the schematic for each side 

### ISSUE THREAD

**Issue by KOEGlike** [Ladniy/jiran-ble-lite#4]
[Example](https://docs.kicad.org/8.0/en/eeschema/eeschema.html#hierarchical_design_examples). Just separate one side of it into a separate file, and in the root sheet reference it twice. 

This project really helped me out in designing my own PCB, so thanks for making it open source!!

**Comment by Ladniy** [comment]
Hi! I've been already using this feature for a long time, these projects just closed source :)

But anyway, thanks for advice and your words!
